#!/bin/bash

if [ -f /opt/apb/bin/activate ] ; then
 source /opt/apb/bin/activate
fi

USER_ID=$(id -u)

if [ x"$USER_ID" != x"0" -a x"$USER_ID" != x"1001" ]; then
    NSS_WRAPPER_PASSWD=/tmp/passwd.nss_wrapper
    NSS_WRAPPER_GROUP=/etc/group

    cp /etc/passwd $NSS_WRAPPER_PASSWD

    echo "${USER_NAME:-apb}:x:$(id -u):0:${USER_NAME:-apb} user:${HOME}:/sbin/nologin" >> $NSS_WRAPPER_PASSWD

    export NSS_WRAPPER_PASSWD
    export NSS_WRAPPER_GROUP

    LD_PRELOAD=/usr/lib64/libnss_wrapper.so
    export LD_PRELOAD
fi

if ! [[ "${MINISHIFT_REGISTRY}" == "" ]]; then
  gid=$(stat -c '%g' ${DOCKER_CERT_PATH}/ca.pem)
else
  gid=$(stat -c '%g' /var/run/docker.sock)
fi

if GROUP=$(getent group -i $gid); then
  group=$(echo $GROUP | awk -F ":" '{ print $1 }')
else
  group=docker
  sudo groupadd $group -g $gid
fi

if [ $UID != 0 ]; then
  sudo usermod -a -G $group apb
fi

command="apb --config /.apb $@"
sg $group -c "$command"
